# Generated by Django 2.0.7 on 2018-07-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0002_auto_20180730_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='psykahut.Game'),
            preserve_default=False,
        ),
    ]
