# Generated by Django 2.0.7 on 2018-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0003_vote_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='questions_asked',
            field=models.ManyToManyField(blank=True, to='psykahut.Question'),
        ),
    ]
