# Generated by Django 2.0.7 on 2018-07-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0004_auto_20180730_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='psykahut.Question'),
        ),
    ]
