# Generated by Django 2.0.7 on 2018-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0005_game_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_psych_answers',
            field=models.IntegerField(default=4),
        ),
    ]
