# Generated by Django 2.0.7 on 2018-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0006_game_num_psych_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
