# Generated by Django 2.0.7 on 2018-07-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0007_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psykahut.Answer'),
        ),
    ]
