# Generated by Django 2.0.7 on 2018-07-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psykahut', '0008_auto_20180730_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='psykahut.Question'),
        ),
    ]
